# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_and_test:
      docker:
        - image: cimg/python:3.10.9
      steps:
        - checkout
        - run:
            name: install via pyproject.toml
            command: pip install -e .'[sphinx,testing]'

        - run:
            name: Run tests
            command: python -m pytest
        - persist_to_workspace:
            root: ~/project
            paths:
              - .

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  cicd:
    jobs:
      - build_and_test
